Repository chocolatey/choco, pull requests merged in 2021-04, with the labels that each got.

#2204 (GH-2203) Get-ChocolateyUnzip add unzipLocation as an alias to Destination
  src/chocolatey.resources/helpers/functions/Get-ChocolateyUnzip.ps1
Labels: 0 - Waiting on User

#2064 (GH-1364) Template create .nuspec encoded without BOM
  src/chocolatey.tests/infrastructure.app/services/TemplateServiceSpecs.cs
  src/chocolatey/infrastructure.app/services/TemplateService.cs
Labels: 0 - Waiting on User

#1852 (maint) Improve log message
  src/chocolatey/infrastructure.app/services/NugetService.cs
Labels: 2 - Working, Documentation

#1436 (GH-1060) Add BeforeInstall parameter to Install-ChocolateyPackage.ps1
  src/chocolatey.resources/helpers/functions/Install-ChocolateyPackage.ps1
Labels: Hacktoberfest

#1925 (GH-1899) Remove unused variables
  src/chocolatey.resources/helpers/functions/Install-ChocolateyPackage.ps1
Labels: Hacktoberfest
