Repository chocolatey/choco, pull requests merged in 2024-12, with the labels that each got.

#3580 (maint) Dont build MSI on the support branch
  recipe.cake
Labels: BuildAutomation, NO RELEASE NOTES

#3586 (release) 1.4.1
  nuspec/chocolatey/chocolatey/tools/chocolateysetup.psm1
  recipe.cake
  src/chocolatey/infrastructure.app/commands/ChocolateyInfoCommand.cs
  src/chocolatey/infrastructure.app/commands/ChocolateyInstallCommand.cs
  src/chocolatey/infrastructure.app/commands/ChocolateyListCommand.cs
  src/chocolatey/infrastructure.app/commands/ChocolateyOutdatedCommand.cs
  src/chocolatey/infrastructure.app/commands/ChocolateySourceCommand.cs
  src/chocolatey/infrastructure.app/commands/ChocolateyUpgradeCommand.cs
  src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
  src/chocolatey/infrastructure.app/nuget/ChocolateyNugetCredentialProvider.cs
  tests/helpers/common/Chocolatey/Disable-ChocolateySource.ps1
  tests/helpers/common/Chocolatey/Enable-ChocolateySource.ps1
  tests/helpers/common/Chocolatey/Get-ChocolateySource.ps1
  tests/pester-tests/BundledApplications.Tests.ps1
  tests/pester-tests/chocolatey.Tests.ps1
  tests/pester-tests/commands/choco-push.Tests.ps1
  tests/pester-tests/features/CredentialProvider.Tests.ps1
Labels: NO RELEASE NOTES

#3585 (release) 2.4.1
  .github/workflows/build.yml
  .teamcity/settings.kts
  recipe.cake
  src/chocolatey.tests.integration/chocolatey.tests.integration.csproj
  src/chocolatey.tests.integration/infrastructure.app/nuget/NugetListSpecs.cs
  src/chocolatey.tests/chocolatey.tests.csproj
  src/chocolatey.tests/infrastructure.app/nuget/ChocolateyNugetCredentialProviderSpecs.cs
  src/chocolatey/infrastructure.app/commands/ChocolateyInfoCommand.cs
  src/chocolatey/infrastructure.app/commands/ChocolateyInstallCommand.cs
  src/chocolatey/infrastructure.app/commands/ChocolateyListCommand.cs
  src/chocolatey/infrastructure.app/commands/ChocolateyOutdatedCommand.cs
  src/chocolatey/infrastructure.app/commands/ChocolateySearchCommand.cs
  src/chocolatey/infrastructure.app/commands/ChocolateyUpgradeCommand.cs
  src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
  src/chocolatey/infrastructure.app/nuget/ChocolateyNugetCredentialProvider.cs
  src/chocolatey/infrastructure.app/nuget/NugetList.cs
  tests/helpers/common/Chocolatey/Disable-ChocolateySource.ps1
  tests/helpers/common/Chocolatey/Enable-ChocolateySource.ps1
  tests/helpers/common/Chocolatey/Get-ChocolateySource.ps1
  tests/pester-tests/commands/choco-push.Tests.ps1
  tests/pester-tests/features/ArgumentsDecryption.Tests.ps1
  tests/pester-tests/features/CredentialProvider.Tests.ps1
  tests/pester-tests/features/UserAgent.Tests.ps1
Labels: NO RELEASE NOTES

#3588 (maint) synced file(s) with chocolatey/.github
  .github/workflows/stale.yml
Labels: BuildAutomation
