Repository chocolatey/choco, pull requests merged in 2025-06, with the labels that each got.

#3679 (maint) Update signature block in Install-ChocolateyZipPackage.ps1
  src/chocolatey.resources/helpers/functions/Install-ChocolateyZipPackage.ps1
Labels: Build Automation

#2857 (#2851) fix license validation output
  src/chocolatey/infrastructure/licensing/LicenseValidation.cs
  tests/pester-tests/features/LimitOutput.Tests.ps1
Labels: hacktoberfest-accepted

#3589 (maint) Correct some typos and fix some tests
  .gitignore
  nuspec/chocolatey/chocolatey/chocolatey.nuspec
  nuspec/chocolatey/chocolatey/tools/chocolateysetup.psm1
  nuspec/chocolatey/chocolatey/tools/init.ps1
  tests/Vagrantfile
  tests/pester-tests/commands/choco-upgrade.Tests.ps1
  tests/pester-tests/powershell-commands/Get-EnvironmentVariableNames.Tests.ps1
Labels: NO RELEASE NOTES

#3716 (maint) synced file(s) with chocolatey/.github
  .github/workflows/top-issues.yml
Labels: Build Automation

#2856 (#2591) Add headers to limit output commands
  src/chocolatey.resources/helpers/ChocolateyTabExpansion.ps1
  src/chocolatey/OutputHelpers.cs
  src/chocolatey/StringResources.cs
  src/chocolatey/chocolatey.csproj
  src/chocolatey/infrastructure.app/ApplicationParameters.cs
  src/chocolatey/infrastructure.app/builders/ConfigurationBuilder.cs
  src/chocolatey/infrastructure.app/commands/ChocolateyApiKeyCommand.cs
  src/chocolatey/infrastructure.app/commands/ChocolateyLicenseCommand.cs
  src/chocolatey/infrastructure.app/commands/ChocolateyPinCommand.cs
  src/chocolatey/infrastructure.app/commands/ChocolateyRuleCommand.cs
  src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
  src/chocolatey/infrastructure.app/services/ChocolateyConfigSettingsService.cs
  src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
  src/chocolatey/infrastructure.app/services/NugetService.cs
  src/chocolatey/infrastructure.app/services/TemplateService.cs
  tests/helpers/common/Chocolatey/Invoke-Choco.ps1
  tests/pester-tests/commands/choco-apikey.Tests.ps1
  tests/pester-tests/features/Headers.Tests.ps1
Labels: hacktoberfest-accepted, Requires Upstream Change
